library(dplyr)
library(ggplot2)
NEI <- readRDS("summarySCC_PM25.rds")
a<-subset(NEI,NEI$fips=="24510")
b<-a %>%group_by(year,type) %>% summarise(Total_Emissions=sum(Emissions))
png(file="plot3.png")
g<-ggplot(b,aes(year,Total_Emissions,col=type))
k<-g+geom_line()+geom_point()+ggtitle("Emissions from Baltimore city")
print(k)
dev.off()