library(dplyr)
library(ggplot2)
NEI <- readRDS("summarySCC_PM25.rds")
x<-subset(NEI,type=="ON-ROAD" & fips=="24510")
y<-x %>%group_by(year,type) %>% summarise(Total_Emissions=sum(Emissions))
s<-subset(NEI,type=="ON-ROAD" & fips=="06037")
r<-s %>%group_by(year,type) %>% summarise(Total_Emissions=sum(Emissions))
colors<-c("Los Angeles"="Steel blue","Baltimore"="purple")
png(file="plot6.png")
k<-ggplot(NULL,aes(year,Total_Emissions))+geom_line(data=r,aes(color="Los Angeles"))+geom_point(data=r,aes(color="Los Angeles"))+geom_line(data=y,aes(color="Baltimore"))+geom_point(data=y,aes(color="Baltimore"))+ scale_color_manual(name="City",values = colors)+ggtitle("Comparison of Los Angeles and Baltimore Motor Vehicle Emissions")
print(k)
dev.off()