library(dplyr)
library(ggplot2)
NEI <- readRDS("summarySCC_PM25.rds")
x<-subset(NEI,type=="ON-ROAD" & fips=="24510")
y<-x %>%group_by(year,type) %>% summarise(Total_Emissions=sum(Emissions))
png(file="plot5.png")
g<-ggplot(y,aes(year,Total_Emissions))+geom_line(col="steel blue")+geom_point(col="steel blue")+ggtitle("Emissions from year 1999-2008 in Baltimore City")
print(g)
dev.off()