---
title: "GVis Practice"
author: "Sneh Bindesh Chitalia"
date: "18/06/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r gv, results='asis',cache=TRUE}
suppressPackageStartupMessages(library(googleVis))
M<-gvisMotionChart(Fruits,"Fruit","Year",options = list(width=600,height=400))
plot(M)
```

```{r gv, results='asis',cache=TRUE}
G<-gvisGeoChart(Exports,locationvar = "Country",colorvar = "Profit",options=list(height=400,width=600))
plot(G)
```

```{r gv, results='asis',cache=TRUE}
G2<-gvisGeoChart(Exports,locationvar = "Country",colorvar = "Profit",options=list(height=400,width=600,region="150"))
plot(G2)
```

```{r linechart,dependson="gv",results="asis", cache=TRUE}
df <- data.frame(label=c("US", "GB", "BR"), val1=c(1,3,4), val2=c(23,12,32))
Line <- gvisLineChart(df, xvar="label", yvar=c("val1","val2"),
        options=list(title="Hello World", legend="bottom",
                titleTextStyle="{color:'red', fontSize:18}",                         
                vAxis="{gridlines:{color:'red', count:3}}",
                hAxis="{title:'My Label', titleTextStyle:{color:'blue'}}",
                series="[{color:'green', targetAxisIndex: 0}, 
                         {color: 'blue',targetAxisIndex:1}]",
                vAxes="[{title:'Value 1 (%)', format:'##,######%'}, 
                                  {title:'Value 2 (\U00A3)'}]",                          
                curveType="function", width=500, height=300                         
                ))
plot(Line)
```

```{r linechart,dependson="gv",results="asis", cache=TRUE}
T1<-gvisTable(Exports,options = list(height=600,width=400))
GT<-gvisMerge(G,T1,horizontal = FALSE)
GTM<-gvisMerge(GT,M,horizontal = TRUE)
plot(GTM)

```
