---
title: "Plotly Practice"
author: "Sneh Bindesh Chitalia"
date: "18/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(plotly)
plot_ly(mtcars, x = ~wt, y = ~mpg, type = "scatter")

```

```{r}
plot_ly(mtcars,x=~wt,y=~mpg,type="scatter",color = ~factor(cyl))
```

```{r}
plot_ly(mtcars,x=~wt,y=~mpg,type="scatter",color=~disp)
```

```{r}
plot_ly(mtcars,x=~wt,y=~mpg,type="scatter",color=~factor(cyl),size=~hp)
```

```{r}
set.seed(123)
temp<-rnorm(100,mean=30,sd=5)
pressure<-rnorm(100)
dtime<-1:100
plot_ly(x=~temp,y=~pressure,z=~dtime,type="scatter3d",color=~temp)
```

```{r}
data("airmiles")
plot_ly(x=~time(airmiles),y=~airmiles,type="scatter",mode="lines")
```

```{r}
library(plotly)
library(tidyr)
library(dplyr)
data("EuStockMarkets")
stocks<-as.data.frame(EuStockMarkets) %>% gather(index,price) %>% mutate(time=rep(time(EuStockMarkets),4))
plot_ly(stocks,x=~time,y=~price,color=~index,type="scatter",mode="lines")
```

```{r}
plot_ly(x=~precip,type="histogram")
```

```{r}
plot_ly(iris,y=~Petal.Length,color=~Species,type="box")
```

```{r}
terrain1<-matrix(rnorm(100*100),nrow=100,ncol=100)
plot_ly(z=~terrain1,type="heatmap")
```

```{r}
state_pop <- data.frame(State = state.abb, Pop = as.vector(state.x77[,1]))
# Create hover text
state_pop$hover <- with(state_pop, paste(State, '<br>', "Population:", Pop))
# Make state borders white
borders <- list(color = toRGB("red"))
# Set up some mapping options
map_options <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)
plot_ly(z = ~state_pop$Pop, text = ~state_pop$hover, locations = ~state_pop$State, 
        type = 'choropleth', locationmode = 'USA-states', 
        color = state_pop$Pop, colors = 'Blues', marker = list(line = borders)) %>%
  layout(title = 'US Population in 1975', geo = map_options)
```