library(data.table)
data<-data.table::fread("household_power_consumption.txt",header=TRUE,na.strings = "?",sep=";")
data$Date<-as.Date(data$Date,"%d/%m/%Y")
data1<-subset(data,Date>=as.Date("2007-2-1") & Date<=as.Date("2007-2-2"))
dateTime<-paste(data1$Date,data1$Time)
dateTime <- setNames(dateTime, "DateTime")
data1<- cbind(dateTime, data1)
data1$dateTime <- as.POSIXct(dateTime)
data1=subset(data1,select=-c(2,3))
png(file="plot2.png",width=480,height=480)
plot(data1$dateTime,data1$Global_active_power,type="l",ylab="Global Active Power (Killowatts)",xlab="")
dev.off()