library(data.table)
data<-data.table::fread("household_power_consumption.txt",header=TRUE,na.strings = "?",sep=";")
data$Date<-as.Date(data$Date,"%d/%m/%Y")
data1<-subset(data,Date>=as.Date("2007-2-1") & Date<=as.Date("2007-2-2"))
dateTime<-paste(data1$Date,data1$Time)
dateTime <- setNames(dateTime, "DateTime")
data1<- cbind(dateTime, data1)
data1$dateTime <- as.POSIXct(dateTime)
data1=subset(data1,select=-c(2,3))
png(file="plot1.png", width=480, height=480)
hist(data1$Global_active_power,data=data1,xlab="Global Active Power (kilowatts)",main="Global Active Power",col="red")
dev.off()